# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.srcs/sources_1/imports/3_Decodeur_Machine_Etats/FSM.vhd
  C:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.srcs/sources_1/imports/3_Decodeur_Machine_Etats/Selector.vhd
  C:/Users/3408804/Downloads/FPGA1_TP1/Partie_2_Cas_Etudes/2_Compteur_Impulsions/impulse_count_.vhd
  C:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.srcs/sources_1/imports/3_Decodeur_Machine_Etats/Top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.srcs/constrs_1/imports/3_Decodeur_Machine_Etats/TOP_Nexys4.xdc
set_property used_in_implementation false [get_files C:/Users/3408804/Downloads/FPGA1_TP1/project_2/project_2.srcs/constrs_1/imports/3_Decodeur_Machine_Etats/TOP_Nexys4.xdc]


synth_design -top Top -part xc7a100tcsg324-3


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
