# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-3
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /users/enseig/phan/fpga2018/tme1/projectX/projectX.cache/wt [current_project]
set_property parent.project_path /users/enseig/phan/fpga2018/tme1/projectX/projectX.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib /users/enseig/phan/fpga2018/resources/FPGA1_TP1/Partie_2_Cas_Etudes/2_Compteur_Impulsions/impulse_count_.vhd
read_xdc /users/enseig/phan/fpga2018/resources/FPGA1_TP1/Partie_2_Cas_Etudes/2_Compteur_Impulsions/Impulse_Count_Nexys4DDR.xdc
set_property used_in_implementation false [get_files /users/enseig/phan/fpga2018/resources/FPGA1_TP1/Partie_2_Cas_Etudes/2_Compteur_Impulsions/Impulse_Count_Nexys4DDR.xdc]

catch { write_hwdef -file IMPULSE_COUNT.hwdef }
synth_design -top IMPULSE_COUNT -part xc7a100tcsg324-3
write_checkpoint -noxdef IMPULSE_COUNT.dcp
catch { report_utilization -file IMPULSE_COUNT_utilization_synth.rpt -pb IMPULSE_COUNT_utilization_synth.pb }
